### ISSUE TITLE
Feature Request: Add support for client-only usage

### ISSUE THREAD

**Issue by ajitzero** [Avansai/properties-file#15] opened 2023-06-15 10:07 UTC
I want to use this for parsing a properties file from the client side to JSON and then upload only the parsed, validated results. Is this all under the scope of this project?

The primary change would be to support File Blob as input and remove a required dependency for `node:fs` or expose the parser function only.

**Comment by nbouvrette** [comment] 2023-06-15 12:05
Hi @ajitzero - which version are you currently using?

In the package's latest version, `getProperties` takes as input either a `string` or a `buffer`. There is no dependency on `node:fs`.

Since your use case is within a browser, you can convert your `Blob` to a `string`, and it should work seamlessly.

Please let me know if I misunderstood your question.

**Comment by ajitzero** [comment] 2023-06-15 15:40
> you can convert your `Blob` to a `string`, and it should work seamlessly.

I see. The example from the README implied this is for server-side usage only (with possibly a file upload pattern). Let me try this and confirm. I'll update and close this as necessary.

**Comment by nbouvrette** [comment] 2023-06-15 19:13
I apologize for any confusion caused by the documentation. Could you please provide more details about the specific part that gives the impression of being limited to server-side usage?

We recently made updates to our documentation due to a previous version containing two different sets of APIs. One set had a dependency on `node:fs`, while the other did not. Explaining this distinction became quite complex, which is why we decided to remove the `node:fs` dependency in the recent updates.

**Comment by nbouvrette** [comment] 2023-06-19 11:45
I'm going to close this due to innactivity. @ajitzero  please le me know if you have suggestions on how to improve the documentation or need anything else.

**Closed as completed by nbouvrette** 2023-06-19 11:45 UTC
